// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"shantaram/app/api"
)

type Menu struct {
	ID      string
	Title   string
	Created time.Time
}

type Migration struct {
	ID      string
	Applied time.Time
}

type Order struct {
	ID            uuid.UUID
	Index         int64
	TableID       *string
	Created       time.Time
	Updated       time.Time
	Status        api.OrderStatus
	ClientName    string
	ClientPhone   string
	ClientComment *string
	Seen          bool
	Items         []api.OrderItem
}

type Product struct {
	ID          uuid.UUID
	GroupID     uuid.UUID
	Index       int32
	Title       string
	Description string
	Price       float32
	Available   bool
	Created     time.Time
	Updated     time.Time
}

type ProductGroup struct {
	ID      uuid.UUID
	MenuID  string
	Index   int32
	Title   string
	Created time.Time
	Updated time.Time
}
